kowenp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('sport/', include('sport.urls')),
]

sport/urls.py
from django.urls import path
from sport import views


app_name = 'sport'
urlpatterns = [
    path('page/<int:customer_pk>/', views.page_ini, name='page'),
    path('new-reservation/<int:customer_pk>/', views.create_reservation, name='new-reservation'),
    path('show-reservation/<int:customer_pk>/', views.show_reservation, name='show-reservation'),
    path('edit-reservation/<int:reservation_pk>/', views.edit_reservation, name='edit-reservation'),
    path('save-reservation/<int:reservation_pk>/', views.confirm_edit_reservation, name='save-reservation'),
    path('delete/<int:reservation_id>/', views.delete_reservation, name='delete'),
    path('new-field/', views.create_field, name='new-field'),
    path('edit-field/<int:field_pk>/', views.edit_field, name='edit-field'),
    path('delete-field/<int:field_pk>/', views.delete_field, name='delete-field'),
    path('show-field/', views.show_field, name='show-field'),
    path('new-company/', views.create_company, name='new-company'),
    path('show-company/', views.show_company, name='show-company'),
    path('edit-company/<int:company_pk>/', views.edit_company, name='edit-company'),
    path('delete-company/<int:company_pk>/', views.delete_company, name='delete-company'),
    path('profile/<int:customer_pk>/', views.profile, name='profile'),
    path('edit-profile/<int:customer_pk>/', views.edit_profile, name='edit-profile'),
]

users/urls.py
from django.urls import path
from users import views


app_name = 'users'
urlpatterns = [
    path('login/', views.login_customer, name='login'),
    path('register/', views.register_customer, name='register'),
]

sport/models.py
from django.db import models
from users.models import Customer
from django.utils import timezone
from django.urls import reverse
import uuid


# Create your models here.


class Field(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE, null=True)
    FIELD_STATUS = (
        ('R', 'Reserved'),
        ('A', 'Available'),
    )
    status = models.CharField(
        max_length=1,
        choices=FIELD_STATUS,
        blank=True,
        default='A',
    )

    TYPE_FIELD = (
        ('1', '5 Players'),
        ('2', '7 Players'),
        ('3', '11 Players'),
    )

    type = models.CharField(
        max_length=1,
        choices=TYPE_FIELD,
        blank=True,
        default='1',
    )

    price = models.CharField(max_length=75)

    def __str__(self):
        return ' Type Field: ' + self.type + ', Price: ' + self.price


class Company(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=25)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name + ' -- ' + self.address


class Reservation(models.Model):
    company_reserve = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    customer_reserve = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='customer_reserve')
    field_reserve = models.ForeignKey(Field, on_delete=models.CASCADE)
    schedule_date = models.DateField(null=True)
    schedule_time = models.TimeField(null=True)

    def __str__(self):
        return 'Company: ' + self.company_reserve.name + 'Address:' + self.company_reserve.address + 'Customer: ' + self.customer_reserve.first_name + ' --- Type Field: --- ' + self.field_reserve.type + ' --- Date Reserved: --- ' \
               + str(self.schedule_date) + ' Schedule Time ' + str(self.schedule_time) + ' --- Price: --- ' + self.field_reserve.price

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('sport:page', args=[str(self.pk)])


class Bill(models.Model):
    reservation = models.OneToOneField(Reservation, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    token = models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')

sport/views.py
from django.shortcuts import render
from sport.models import Field, Company, Reservation, Bill
from users.models import Customer
from django.shortcuts import HttpResponseRedirect, reverse, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def page_ini(request, customer_pk):
    template = 'sport/page.html',
    context = {
        'customer': customer_pk,
    }
    return render(request,  template, context)


def create_reservation(request, customer_pk):
    if request.method == 'POST':
        post_customer = Customer.objects.get(pk=request.POST['customer'])
        post_field = Field.objects.get(pk=request.POST['field'])
        post_company = Company.objects.get(pk=request.POST['company'])
        new_reservation_customer=Reservation(
            schedule_date=request.POST['schedule_date'],
            schedule_time=request.POST['schedule_time'],
            customer_reserve=post_customer,
            field_reserve=post_field,
            company_reserve=post_company,
        )
        new_reservation_customer.save()
        return HttpResponseRedirect(reverse('sport:show-reservation', kwargs={'customer_pk': request.POST['customer']}))
    elif request.method == 'GET':
        template = 'sport/reservation.html'
        context = {
            'customer': Customer.objects.get(pk=customer_pk),
            'fields': Field.objects.all(),
            'companies': Company.objects.all(),
        }
        return render(request, template, context)
    return HttpResponse('No se puede guardar')


def show_reservation(request, customer_pk):
    template = 'sport/show_reservation.html'
    reservation_customer = Reservation.objects.filter(customer_reserve=customer_pk)
    paginator = Paginator(reservation_customer, 10)
    try:
        reservation = reservation_customer
    except PageNotAnInteger:
        reservation = reservation_customer
    except EmptyPage:
        reservation = reservation_customer

    return render(request, template, {'reservation': reservation, 'customer_pk': customer_pk}, {'paginator': paginator}) # FALTABA AGREGAR EL CUSTOMERPK POR ALGUNA RAZON NO IBA DENTRO DEL RESERVATION


def edit_reservation(request, reservation_pk):
    template = 'sport/edit_reservation.html'
    company_reserve = Reservation.objects.get(pk=reservation_pk)
    field_reserve = Reservation.objects.get(pk=reservation_pk)
    context = {
        'reservation': Reservation.objects.get(pk=reservation_pk),
        'companies': Company.objects.all(),
        'fields': Field.objects.all(),
        'company_instance': company_reserve,
        'field_instance': field_reserve,
    }

    return render(request, template, context)


def confirm_edit_reservation(request, reservation_pk):
    if request.method == 'POST':
        post_company = Company.objects.get(pk=request.POST['company'])
        post_field = Field.objects.get(pk=request.POST['field'])
        updated_reservation = Reservation.objects.get(pk=reservation_pk)
        updated_reservation.schedule_date = request.POST['schedule_date']
        updated_reservation.schedule_time = request.POST['schedule_time']
        updated_reservation.company_reserve = post_company
        updated_reservation.field_reserve = post_field
        updated_reservation.save()

        return HttpResponseRedirect(reverse('sport:show-reservation', kwargs={'customer_pk': updated_reservation.customer_reserve.id}))
    return HttpResponse('Error: method not allowed.')


def delete_reservation(request, reservation_id):
    deleted_reservation = Reservation.objects.get(id=reservation_id)
    deleted_reservation.delete()

    return HttpResponseRedirect(reverse('sport:show-reservation',  kwargs={'customer_pk': deleted_reservation.customer_reserve.id}))


def create_field(request):
    if request.method == 'POST':
        post_company = Company.objects.get(pk=request.POST['company'])
        new_field = Field(
            company=post_company,
            status=request.POST['status'],
            type=request.POST['type'],
            price=request.POST['price'],
        )
        new_field.save()
        return HttpResponseRedirect(reverse('sport:show-field'))
    elif request.method == 'GET':
        template = 'sport/new_field.html'
        context = {
            'companies': Company.objects.all(),
        }
        return render(request, template, context)
    return HttpResponse('No se puede guardar')


def show_field(request):
    template = 'sport/show_field.html'
    list_field = Field.objects.all()

    paginator = Paginator(list_field, 10)
    try:
        field_list = list_field
    except PageNotAnInteger:
        field_list = list_field
    except EmptyPage:
        field_list = list_field

    return render(request, template, {'field_list': field_list}, {'paginator': paginator})


def edit_field(request, field_pk):
    if request.method == 'POST':
        updated_field = Field.objects.get(pk=field_pk)
        updated_field.status = request.POST['status']
        updated_field.type = request.POST['type']
        updated_field.price = request.POST['price']
        updated_field.save()

        return HttpResponseRedirect(reverse('sport:show-field'))
    elif request.method == 'GET':
        template = 'sport/edit_field.html'
        context = {
            'field': Field.objects.get(pk=field_pk)
        }
        return render(request, template, context)
    return HttpResponse('Error: method not allowed.')


def delete_field(request, field_pk):
    deleted_field = Field.objects.get(id=field_pk)
    deleted_field.delete()

    return HttpResponseRedirect(reverse('sport:show-field'))


def create_company(request):
    if request.method == 'POST':
        new_company = Company(
            name=request.POST['name'],
            address=request.POST['address'],
            phone=request.POST['phone'],
            email=request.POST['email'],
        )
        new_company.save()
        return HttpResponseRedirect(reverse('sport:show-company'))
    elif request.method == 'GET':
        template = 'sport/create_company.html'
        return render(request, template)
    return HttpResponse('No se puede guardar')


def show_company(request):
    template = 'sport/show_company.html'
    list_company = Company.objects.all()

    paginator = Paginator(list_company, 10)
    try:
        company_list = list_company
    except PageNotAnInteger:
        company_list = list_company
    except EmptyPage:
        company_list = list_company

    return render(request, template, {'company_list': company_list}, {'paginator': paginator})


def edit_company(request, company_pk):
    if request.method == 'POST':
        updated_company = Company.objects.get(pk=company_pk)
        updated_company.name = request.POST['name']
        updated_company.address = request.POST['address']
        updated_company.phone = request.POST['phone']
        updated_company.email = request.POST['email']
        updated_company.save()

        return HttpResponseRedirect(reverse('sport:show-company'))
    elif request.method == 'GET':
        template = 'sport/edit_company.html'
        context = {
            'company': Company.objects.get(pk=company_pk)
        }
        return render(request, template, context)
    return HttpResponse('Error: method not allowed.')


def delete_company(request, company_pk):
    deleted_company = Company.objects.get(id=company_pk)
    deleted_company.delete()

    return HttpResponseRedirect(reverse('sport:show-company'))


def profile(request, customer_pk):
    template = 'sport/profile.html'
    context = {
        'customer': Customer.objects.get(pk=customer_pk),
        'reservation': Reservation.objects.filter(customer_reserve=customer_pk).count(),
        'field': Field.objects.all(),
    }
    return render(request, template, context)


def edit_profile(request, customer_pk):
    if request.method == 'POST':
        updated_profile = Customer.objects.get(pk=customer_pk)
        updated_profile.first_name = request.POST['first_name']
        updated_profile.last_name = request.POST['last_name']
        updated_profile.phone = request.POST['phone']
        updated_profile.email = request.POST['email']
        updated_profile.address = request.POST['address']
        updated_profile.password = request.POST['password']
        updated_profile.save()
        return HttpResponseRedirect(reverse('sport:profile',  kwargs={'customer_pk': customer_pk}))
    elif request.method == 'GET':
        template = 'sport/edit_profile.html'
        context = {
            'customer': Customer.objects.get(pk=customer_pk)
        }
        return render(request, template, context)
    return HttpResponse('Error: method not allowed.')

sport/templates/sport/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Sport</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link href="https://fonts.googleapis.com/css?family=Allerta+Stencil|Audiowide|Nunito:600&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  		<link href="https://fonts.googleapis.com/css?family=Ubuntu:700&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Allerta+Stencil|Audiowide|Ubuntu&display=swap" rel="stylesheet">
		        {% load static %}
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>

	</head>

<body>
        {% block content %}
        {% endblock %}
            <script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
			<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

sport/templates/sport/create_company.html
{% extends "sport/base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="body">
    <header id="header">
	<div class="inner">
			<a class="logo">
                {% load static %}
				<span class="symbol"><img src="{% static 'imagess/ball.svg' %}" alt="" /></span><span class="title">Sport Center</span>
			</a>
			<nav>
				<ul>
					<li><a href="#menu">Menu</a></li>
				</ul>
			</nav>

	</div>
</header>

<nav id="menu">
	<h2>Menu</h2>
	<ul>
		<li><a href="{% url 'sport:show-company' %}">Regresar</a></li>
		<li><a href="">Cerrar Sesión</a></li>
	</ul>
</nav>
    <h1>Agregar Centro Deportivo</h1>
<form action="{% url 'sport:new-company' %}" method="POST">
        {% csrf_token %}
        <p>
        <div class="form-group">
            <label>Nombre:</label>
            <input type="text" class="form-control inputs"  name="name" required>
        </div>
        </p>

        <p>
        <div class="form-group">
            <label>Dirección:</label>
            <input type="text" class="form-control inputs"  name="address" required>
        </div>
        </p>

        <p>
        <div class="form-group">
            <label>Teléfono:</label>
            <input type="text" class="form-control inputs"  name="phone" required>
        </div>
        </p>

        <p>
        <div class="form-group">
            <label>Correo Electrónico:</label>
            <input type="text" class="form-control inputs"  name="email" required>
        </div>
        </p>
        <button type="submit" class="btn btn-outline-success btn-lg">Agregar</button>
    </form>
</div>
</body>
</html>
{% endblock %}

sport/templates/sport/edit_company.html
{% extends "sport/base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="body">
    <header id="header">
	<div class="inner">
			<a class="logo">
                {% load static %}
				<span class="symbol"><img src="{% static 'imagess/ball.svg' %}" alt="" /></span><span class="title">Sport Center</span>
			</a>
			<nav>
				<ul>
					<li><a href="#menu">Menu</a></li>
				</ul>
			</nav>

	</div>
</header>

<nav id="menu">
	<h2>Menu</h2>
	<ul>
		<li><a href="{% url 'sport:show-company' %}">Cancelar</a></li>
		<li><a href="">Cerrar Sesión</a></li>
	</ul>
</nav>
    <h1>Editar Centro Deportivo</h1>
<form action="{% url 'sport:edit-company' company.pk %}" method="POST">
        {% csrf_token %}
        <p>
        {% if company %}
        <div class="form-group">
            <label>Nombre:</label>
            <input type="text" name="name" class="form-control inputs" value="{{ company.name }}">
        </div>
        </p>
        <div class="form-group">
            <label>Dirección</label>
            <input type="text" name="address" class="form-control inputs" value="{{ company.address }}">
        </div>
        </p>
        <div class="form-group">
            <label>Teléfono:</label>
            <input type="text" name="phone" class="form-control inputs" value="{{ company.phone }}">
        </div>
        </p>
        <div class="form-group">
            <label>Correo Electrónico:</label>
            <input type="text" name="email" class="form-control inputs" value="{{ company.email }}">
        </div>
        </p>
        {% endif %}
        <button type="submit" class="btn btn-warning btn-lg">Editar</button>
        <a href=""><button type="submit" class="btn btn-danger btn-lg">Cancelar</button></a>
    </form>
</div>
</body>
</html>
{% endblock %}

sport/templates/sport/edit_field.html
{% extends "sport/base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="body">
    <header id="header">
	<div class="inner">
			<a class="logo">
                {% load static %}
				<span class="symbol"><img src="{% static 'imagess/ball.svg' %}" alt="" /></span><span class="title">Sport Center</span>
			</a>
			<nav>
				<ul>
					<li><a href="#menu">Menu</a></li>
				</ul>
			</nav>

	</div>
</header>

<nav id="menu">
	<h2>Menu</h2>
	<ul>
		<li><a href="{% url 'sport:show-field' %}">Cancelar</a></li>
		<li><a href="">Cerrar Sesión</a></li>
	</ul>
</nav>
    <h1>Editar Cancha</h1>
<form action="{% url 'sport:edit-field' field.pk %}" method="POST">
        {% csrf_token %}
        <p>
        <div class="form-group">
            <label>Status</label>
            <select class="form-control input" name="status">
                <option value="R" {% if field.status == 'R' %} selected="selected" {% endif %}>Reserved</option>
                <option value="A" {% if field.status == 'A' %} selected="selected" {% endif %}>Available</option>
            </select>
        </div>
        </p>
      <p>
        <div class="form-group">
            <label>Type of Field</label>
            <select class="form-control input" name="type">
                <option value="1" {% if field.type == '1' %} selected="selected" {% endif %}>5 Players</option>
                <option value="2" {% if field.type == '2' %} selected="selected" {% endif %}>7 Players</option>
                <option value="3" {% if field.type == '3' %} selected="selected" {% endif %}>11 Players</option>
            </select>
        </div>
        </p>
        <p>
        <div class="form-group">
            <label>Price</label>
            <input type="text" class="form-control inputs"  name="price"  value="{{ field.price }}" required>
        </div>
        </p>
        <button type="submit" class="btn btn-warning btn-lg">Editar</button>
        <a href=""><button type="submit" class="btn btn-danger btn-lg">Cancelar</button></a>
    </form>
</div>
</body>
</html>
{% endblock %}

sport/templates/sport/edit_profile.html
{% extends "sport/base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="body">
    <header id="header">
	<div class="inner">
			<a class="logo">
                {% load static %}
				<span class="symbol"><img src="{% static 'imagess/ball.svg' %}" alt="" /></span><span class="title">Sport Center</span>
			</a>
			<nav>
				<ul>
					<li><a href="#menu">Menu</a></li>
				</ul>
			</nav>

	</div>
</header>

<nav id="menu">
	<h2>Menu</h2>
	<ul>
        <li><a href="{% url 'sport:page' customer.pk %}">Inicio</a></li>
		<li><a href="{% url 'sport:profile' customer.pk %}">Cancelar</a></li>
		<li><a href="{% url 'users:login' %}">Cerrar Sesión</a></li>
	</ul>
</nav>
    <h1>Editar Mi Perfil</h1>
<form action="{% url 'sport:edit-profile' customer.pk %}" method="POST">
        {% csrf_token %}
        <p>
        {% if customer %}
        <div class="form-group">
            <label>Nombre:</label>
            <input type="text" name="first_name" class="form-control inputs" value="{{ customer.first_name }}">
        </div>
        </p>
        <div class="form-group">
            <label>Apellidos:</label>
            <input type="text" name="last_name" class="form-control inputs" value="{{ customer.last_name }}">
        </div>
        </p>
        <div class="form-group">
            <label>Teléfono:</label>
            <input type="text" name="phone" class="form-control inputs" value="{{ customer.phone }}">
        </div>
        </p>
        <div class="form-group">
            <label>Correo Electrónico:</label>
            <input type="text" name="email" class="form-control inputs" value="{{ customer.email }}">
        </div>
        </p>
        <div class="form-group">
            <label>Dirección:</label>
            <input type="text" name="address" class="form-control inputs" value="{{ customer.address }}">
        </div>
        </p>
        <div class="form-group">
            <label>Password:</label>
            <input type="password" name="password" class="form-control inputs" value="{{ customer.password }}">
        </div>
        </p>
        {% endif %}
        <button type="submit" class="btn btn-warning btn-lg">Editar</button>
        <a href=""><button type="submit" class="btn btn-danger btn-lg">Cancelar</button>
    </form>
</div>
</body>
</html>
{% endblock %}

sport/templates/sport/profile.html
{% extends "sport/base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Compañías</title>
</head>
<body>
	<div id="body">
		<header id="header">
		<div class="inner">
			<a class="logo">
				{% load static %}
				<span class="symbol"><img src="{% static 'imagess/ball.svg' %}" alt="" /></span><span class="title">Sport Center</span>
			</a>
			<nav>
				<ul>
					<li><a href="#menu">Menu</a></li>
				</ul>
			</nav>
		</div>
	</header>
	<nav id="menu">
		<h2>Menu</h2>
		<ul>
			<li><a href="{% url 'sport:page' customer.pk %}">Inicio</a></li>
			<li><a href="{% url 'sport:edit-profile' customer.pk %}">Editar Perfil</a></li>
			<li><a href="{% url 'users:login' %}">Cerrar Sesión</a></li>
		</ul>
	</nav>
		<h1>MI PERFIL</h1>
			<label>Cliente: {{ customer.first_name}} {{ customer.last_name }}</label>
			<label>Teléfono: {{ customer.phone}}</label>
			<label>Correo Electrónico: {{ customer.email}}</label>
			<label>Dirección: {{ customer.address}}</label>


		<label><a href="{% url 'sport:show-reservation' customer.pk %}">Reservaciones: {{ reservation }}</a></label>
</body>
</html>

{% endblock %}

sport/templates/sport/show_company.html
{% extends "sport/base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Compañías</title>
</head>
<body>
<div id="body">
    <header id="header">
	<div class="inner">
			<a class="logo">
                {% load static %}
				<span class="symbol"><img src="{% static 'imagess/ball.svg' %}" alt="" /></span><span class="title">Sport Center</span>
			</a>
			<nav>
				<ul>
					<li><a href="#menu">Menu</a></li>
				</ul>
			</nav>

	</div>
</header>

<nav id="menu">
	<h2>Menu</h2>
	<ul>
        <li><a href="">Inicio</a></li>
		<li><a href="{% url 'sport:new-company' %}">Agregar Centro Deportivo</a></li>
	</ul>
</nav>
    <h1>Centro Deportivo</h1>
 <table class="table table-bordered table-sm tablesita">
     <thead class="thead-dark thr">
            <tr>
                <th>COMPAÑÍA</th>
                <th>DIRECCIÓN</th>
                <th>TELEFÓNO</th>
                <th>CORREO ELECTRÓNICO</th>
                <th>OPCIONES</th>
            </tr>
      </thead>
            {% for company in company_list %}
            <tr>
                <td>{{ company.name }}</td>
                <td>{{ company.address }}</td>
                <td>{{ company.phone }}</td>
                <td>{{ company.email }}</td>
                <td>
                    <a href="{% url 'sport:delete-company' company.pk %}"><button type="button" class="btn btn-danger">Eliminar</button></a>
                    <a href="{% url 'sport:edit-company' company.pk %}"><button type="button" class="btn btn-warning">Editar</button></a>
                </td>
            </tr>
            {% endfor %}

        </table>
{% if company_list.has_other_pages %}
  <ul class="pagination">
    {% if company_list.has_previous %}
      <li><a href="?page={{ available.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in company_list.paginator.page_range %}
      {% if company_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if company_list.has_next %}
      <li><a href="?page={{ available.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
</body>
</html>
{% endif %}

{% endblock %}

sport/templates/sport/show_field.html
{% extends "sport/base.html" %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="body">
    <header id="header">
	<div class="inner">
			<a class="logo">
                {% load static %}
				<span class="symbol"><img src="{% static 'imagess/ball.svg' %}" alt="" /></span><span class="title">Sport Center</span>
			</a>
			<nav>
				<ul>
					<li><a href="#menu">Menu</a></li>
				</ul>
			</nav>

	</div>
</header>

<nav id="menu">
	<h2>Menu</h2>
	<ul>
		<li><a href="{% url 'sport:new-field' %}">Agregar Cancha</a></li>
	</ul>
</nav>
    <h1>Canchas</h1>
 <table class="table table-bordered table-sm tablesita">
     <thead class="thead-dark thr">
            <tr>
                <th>COMPAÑÍA</th>
                <th>ESTADO</th>
                <th>CANCHA - TIPO DE CANCHA</th>
                <th>PRECIO</th>
                <th>OPCIONES</th>
            </tr>
      </thead>
            {% for field in field_list %}
            <tr>
                <td>{{ field.company }}</td>
                <td>{{ field.status }}</td>
                <td>{{ field.type }}</td>
                <td>{{ field.price }}</td>
                <td>
                    <a href="{% url 'sport:delete-field' field.pk %}"><button type="button" class="btn btn-danger">Eliminar</button></a>
                    <a href="{% url 'sport:edit-field' field.pk %}"><button type="button" class="btn btn-warning">Editar</button></a>
                </td>
            </tr>
            {% endfor %}

        </table>
{% if field_list.has_other_pages %}
  <ul class="pagination">
    {% if field_list.has_previous %}
      <li><a href="?page={{ available.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in field_list.paginator.page_range %}
      {% if field_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if field_list.has_next %}
      <li><a href="?page={{ available.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
</body>
</html>
{% endif %}

{% endblock %}